import 'dart:convert';

//THIS MODEL CODE IS GENERATED BY WEBSITE - https://quicktype.io/

Welcome welcomeFromJson(String str) => Welcome.fromJson(json.decode(str));

String welcomeToJson(Welcome data) => json.encode(data.toJson());

class Welcome {
  final String type;
  final String duration;
  final String solid;
  final String time;
  final String date;

  const Welcome({
    required this.type,
    required this.duration,
    required this.solid,
    required this.time,
    required this.date,
  });

  factory Welcome.fromJson(Map<String, dynamic> json) => Welcome(
    type: json["type"],
    duration: json["duration"],
    solid: json["solid"],
    time: json["time"],
    date: json["date"],
  );

  Map<String, dynamic> toJson() => {
    "type": type,
    "duration": duration,
    "solid": solid,
    "time": time,
    "date": date,
  };
}
