

//THIS MODEL CODE IS GENERATED BY WEBSITE - https://quicktype.io/
import 'dart:convert';

HW welcomeFromJson(String str) => HW.fromJson(json.decode(str));

String welcomeToJson(HW data) => json.encode(data.toJson());

class HW {
  final String hight;
  final String weight;
  final String date;
  final String time;

  HW({
    required this.hight,
    required this.weight,
    required this.date,
    required this.time,
  });

  factory HW.fromJson(Map<String, dynamic> json) => HW(
    hight: json["hight"],
    weight: json["weight"],
    date: json["date"],
    time: json["time"],
  );

  Map<String, dynamic> toJson() => {
    "hight": hight,
    "weight": weight,
    "date": date,
    "time": time,
  };
}
