
import 'dart:convert';

//THIS MODEL CODE IS GENERATED BY WEBSITE - https://quicktype.io/

Napy nappyFromJson(String str) => Napy.fromJson(json.decode(str));

String welcomeToJson(Napy data) => json.encode(data.toJson());

class Napy {
  final String type;
  final String time;
  final String date;

  Napy({
    required this.type,
    required this.time,
    required this.date,
  });

  factory Napy.fromJson(Map<String, dynamic> json) => Napy(
    type: json["type"],
    time: json["time"],
    date: json["date"],
  );

  Map<String, dynamic> toJson() => {
    "type": type,
    "time": time,
    "date": date,
  };
}
