
//THIS MODEL CODE IS GENERATED BY WEBSITE - https://quicktype.io/
import 'dart:convert';

Slep welcomeFromJson(String str) => Slep.fromJson(json.decode(str));

String welcomeToJson(Slep data) => json.encode(data.toJson());

class Slep {
  final String itime;
  final String ftime;
  final String details;

  Slep({
    required this.itime,
    required this.ftime,
    required this.details,
  });

  factory Slep.fromJson(Map<String, dynamic> json) => Slep(
    itime: json["itime"],
    ftime: json["ftime"],
    details: json["details"],
  );

  Map<String, dynamic> toJson() => {
    "itime": itime,
    "ftime": ftime,
    "details": details,
  };
}
